name: test and build
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: apt deps
        shell: bash
        run: sudo apt-get install luarocks liblua5.4-dev lua5.4 lcov socat
      - name: check for lua
        shell: bash
        run: which echo && which lua && which lua5.4 && lua -v && lua5.4 -v
      - name: luarocks deps
        shell: bash
        run: echo luacov luacov-reporter-lcov | xargs -n1 sudo luarocks install --lua-version=5.4
      - name: Stylua
        run: |
          wget -O /tmp/stylua.zip https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.2/stylua-linux-x86_64.zip
          sudo unzip /tmp/stylua.zip -d /usr/local/bin/
      - name: Get Short Git Hash
        shell: bash
        run: echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        # thanks https://stackoverflow.com/a/61699863
      - name: test
        run: make test-all
        # run: eval "$(luarocks --lua-version 5.4 path --bin)" && make test-all
      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
      - name: build
        run: GIT_HASH=${{ env.sha_short }} make serial-keyboard.deb
      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v2
        with:
          name: serial-keyboard-${{ env.sha_short }}.deb
          path: ./serial-keyboard.deb
