name: test and build
on:
  push:
    branches:
      - master
      - test-*
  schedule:
    - cron: '0 0 1 * *'

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install bashcov
        shell: bash
        run: sudo gem install bashcov simplecov-lcov
      - name: apt deps
        shell: bash
        run: sudo apt-get install luarocks liblua5.4-dev lua5.4 lcov socat
      - name: check for lua
        shell: bash
        run: which echo && which lua && which lua5.4 && lua -v && lua5.4 -v
      - name: luarocks deps
        shell: bash
        run: echo luacov luacov-reporter-lcov luassert | xargs -n1 sudo luarocks install --lua-version=5.4
      - name: Stylua
        run: |
          wget -O /tmp/stylua.zip https://github.com/JohnnyMorganz/StyLua/releases/download/v0.18.2/stylua-linux-x86_64.zip
          sudo unzip /tmp/stylua.zip -d /usr/local/bin/
      - name: test
        run: make
        # run: eval "$(luarocks --lua-version 5.4 path --bin)" && make test-all
      - name: add more info
        shell: bash
        run: mkdir report/debug && cp *.info report/debug
      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./report
      - name: coverage check
        shell: bash
        run: make coverage-check
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Short Git Hash
        shell: bash
        run: echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        # thanks https://stackoverflow.com/a/61699863
      - name: apt deps
        shell: bash
        run: sudo apt-get install liblua5.4-dev lua5.4
      - name: build
        run: GIT_HASH=${{ env.sha_short }} make -C driver -f package.mk serial-keyboard.deb
      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v2
        with:
          name: serial-keyboard-${{ env.sha_short }}.deb
          path: ./driver/serial-keyboard.deb
  subprojects-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cc: gcc
            option:
          - cc: clang
            option: CC=clang
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: apt deps
        shell: bash
        run: sudo apt-get install luarocks liblua5.4-dev lua5.4 socat
      - name: check for lua
        shell: bash
        run: which echo && which lua && which lua5.4 && lua -v && lua5.4 -v
      - name: luarocks deps
        shell: bash
        run: sudo luarocks install --lua-version=5.4 luassert
      - name: test firmware subproject
        run: make -C firmware test ${{ matrix.option }}
      - name: test driver subproject
        run: make -C driver test ${{ matrix.option }}
      - name: ${{ matrix.cc }} check
        shell: bash
        run: find . -name '*.o' | xargs readelf -p .comment | grep -i ${{ matrix.cc }}
      - name: only ${{ matrix.cc }} check
        shell: bash
        run: |
          OTHER_COMPILER=$(echo clang gcc | xargs -n1 echo | grep -v ${{ matrix.cc }})
          echo make sure we are not accidentally using $OTHER_COMPILER
          ! find . -name '*.o' | xargs readelf -p .comment | grep -i $OTHER_COMPILER
      - name: no runtime or compiletime coverage info
        shell: bash
        run: |
          ! find . -name 'luacov*' -o -name '*.gc*' | grep '.'
      - name: publish
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: report
